In [46]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [47]:
f = lambda x: x**3 - 10*x**2 + 5

In [48]:
def incremental(f,x0,b,h):
    x1 = x0 + h
    n = 1
    while f(x0)>0 and f(x1)>0:
        if x1 > b:
            return "None"
        x0 = x1
        x1 = x0 + h
        n+=1
    return x1, n

In [49]:
reference = 0.7346035077893032
rows = []
tolerances = []

for i in range(1, 6):
    tol = 10**(-i)
    root, steps = incremental(f, 0, 1, tol)
    error = abs(reference - root)/reference*100
    tolerances.append(tol)
    rows.append([root, steps, error])

columns = ['Root', 'Steps', 'Error %']
pd.DataFrame(rows, index=tolerances, columns=columns)

            Root  Steps   Error %
0.10000  0.80000      8  8.902284
0.01000  0.74000     74  0.734613
0.00100  0.73500    735  0.053974
0.00010  0.73470   7347  0.013135
0.00001  0.73461  73461  0.000884

In [50]:
def bisection(f,x0,x1,tol):
    n = 1
    while abs(x0-x1)>tol:
        x2 = (x0+x1)/2
        if f(x0)*f(x2)<0:
            x1=x2
        if f(x1)*f(x2)<0:
            x0=x2
        n+=1
    return x1,n

In [51]:
reference = 0.7346035077893032
rows = []
tolerances = []

for i in range(1, 6):
    tol = 10**(-i)
    root, steps = bisection(f, 0, 1, tol)
    error = abs(reference - root)/reference*100
    tolerances.append(tol)
    rows.append([root, steps, error])

columns = ['Root', 'Steps', 'Error %']
pd.DataFrame(rows, index=tolerances, columns=columns)

             Root  Steps   Error %
0.10000  0.750000      5  2.095891
0.01000  0.742188      8  1.032393
0.00100  0.735352     11  0.101831
0.00010  0.734619     15  0.002128
0.00001  0.734604     18  0.000051